// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtX4KtC6nZvhFa1s3WzJ03tzKmCdnyiDo',
    appId: '1:893558834988:web:2505beae93b9b373510e89',
    messagingSenderId: '893558834988',
    projectId: 'photo-gallery-bloc-app',
    authDomain: 'photo-gallery-bloc-app.firebaseapp.com',
    storageBucket: 'photo-gallery-bloc-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNh8e71Mv9rTc2A7MKclN913qx0XhvQPI',
    appId: '1:893558834988:android:084db23379f0ba40510e89',
    messagingSenderId: '893558834988',
    projectId: 'photo-gallery-bloc-app',
    storageBucket: 'photo-gallery-bloc-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAcRMU7pnCDCUMUfiOngCMWh2K98ubliA',
    appId: '1:893558834988:ios:673392484419d7ed510e89',
    messagingSenderId: '893558834988',
    projectId: 'photo-gallery-bloc-app',
    storageBucket: 'photo-gallery-bloc-app.appspot.com',
    iosClientId: '893558834988-2a7bk82rsd7dd28b24q3lo5qm24q6h0o.apps.googleusercontent.com',
    iosBundleId: 'com.example.photoGallery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAcRMU7pnCDCUMUfiOngCMWh2K98ubliA',
    appId: '1:893558834988:ios:7b3c0b2df761c3a2510e89',
    messagingSenderId: '893558834988',
    projectId: 'photo-gallery-bloc-app',
    storageBucket: 'photo-gallery-bloc-app.appspot.com',
    iosClientId: '893558834988-n5rg4hkgfkdvp105tfvvlmhdt0qnsmeu.apps.googleusercontent.com',
    iosBundleId: 'com.example.photoGallery.RunnerTests',
  );
}
